### ISSUE TITLE
Navigation arrows crash

### ISSUE THREAD

**Issue by PingForward** [alkurop/steet_view_markers#1]
Some locations don't have navigation arrows (34.2022332,-118.3910608)
[link](https://www.google.by/maps/place/34%C2%B012'07.9%22N+118%C2%B023'27.9%22W/@34.2022332,-118.3910608,3a,75y,256.06h,67.99t/data=!3m7!1e1!3m5!1scvqa086uDwy5UucL5UUt5Q!2e0!6s%2F%2Fgeo0.ggpht.com%2Fcbk%3Fpanoid%3Dcvqa086uDwy5UucL5UUt5Q%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D68.479744%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!4m5!3m4!1s0x0:0x0!8m2!3d34.202183!4d-118.391077?hl=en)
But for some reason they appear in your lib, and if you press one the app crashes.

**Comment by alkurop** [comment]
This might be caused by an old play-services-maps version. please use 11.0.1
Do you still experience it?
If so provide a stacktrace
